// <auto-generated />
using DeliveryFeeApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliveryFeeApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250311160223_UpdateStationWeather")]
    partial class UpdateStationWeather
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("DeliveryFeeApi.Data.StationWeather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AirTemp")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationName")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VmoCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeatherPhenomenon")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WindSpeed")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StationWeathers");
                });
#pragma warning restore 612, 618
        }
    }
}
